server:
  port: 8080

spring:
  application:
    name: api-gateway
  config:
    import: "optional:configserver:http://localhost:8888"

---
# Docker profile
spring:
  config:
    activate:
      on-profile: docker
    import: "optional:configserver:http://hc-config-server:8888"

eureka:
  client:
    service-url:
      defaultZone: http://hc-eureka-server:8761/eureka/
