spring.application.name=notification-service

# Config Server
spring.config.import=optional:configserver:http://localhost:8888
spring.cloud.config.fail-fast=false

# Minimal Eureka bootstrap
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/

---
# Docker Profile
spring.config.activate.on-profile=docker
spring.config.import=optional:configserver:http://config:config123@hc-config-server:8888
eureka.client.service-url.defaultZone=http://hc-eureka-server:8761/eureka/
